<a href="https://colab.research.google.com/github/meisicat/Test1/blob/main/WENZEL_Lab_1_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

In [ ]:
2*24

48

In [ ]:
2**8

256

In [ ]:
8//4

2

In [ ]:
13%12

1

In [ ]:
22%12

10

#variables

In [ ]:
apples=5

In [ ]:
apples

5

In [ ]:
oranges=8

In [ ]:
oranges+apples

13

In [ ]:
total = oranges + apples

In [ ]:
total

13

In [ ]:
apple**2

25

In [ ]:
cost_per_apple=0.25

In [ ]:
total_apple_cost=apple*cost_per_apple

In [ ]:
total_apple_cost

1.25

In [ ]:
blouse_cost=90

In [ ]:
heel_cost=50  

In [ ]:
jean_cost=15

In [ ]:
blouse_sold=10

In [ ]:
jean_sold=9

In [ ]:
heel_sold=30

In [ ]:
total_sales = ( blouse_cost * blouse_sold ) + ( jean_cost * jean_sold ) + ( heel_cost * heel_sold )

In [ ]:
total_sales #dollar currency

2535

In [ ]:
total_shirt_sales + total_blouse_sales + total_heel_sales

NameError: ignored

# vectors

In [ ]:
import numpy as np

In [ ]:
import matplotlib as plt

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = np.arange(10)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
y

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [ ]:
y+1

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [ ]:
y**2

array([  25,   64,  121,  196,  289,  400,  529,  676,  841, 1024])

In [ ]:
y*2

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = 3 * x + 5

In [ ]:
plt.plot(x,y,'.') #explain all of this 

AttributeError: ignored

In [ ]:
plt.plot*x,y,'.')

SyntaxError: ignored

In [ ]:
plt.plot(x,y,'r--')

AttributeError: ignored

In [ ]:
plt.plot(x,y,marker = 'o'
            linestyle = 'none',
            markerfacecolor='#57D91F')

SyntaxError: ignored

In [ ]:
np.linespace(0,5,10)

AttributeError: ignored

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
plt.plot(x,y,marker = '0',linestyle= 'none'.markerfacecolor='#57D91F')
plt.title("my first graph");
plt.xlabel("x axis label goes here")
plt.ylabel("y axis label goes here")

SyntaxError: ignored

In [ ]:
plt.plot(x,y,marker = '0',linestyle= 'none'.markerfacecolor='#57D91F')
plt.title("my first graph");
plt.xlabel("x axis label goes here")
plt.ylabel("y axis label goes here")
plt.legend()

SyntaxError: ignored

In [ ]:
x=np.linespace(0,2,100)

plt.plot(x,x label="linear")
plt.plot(x,x**2, label="linear")
plt.plot(x,x**3, label="cubed")
plt.legend()

SyntaxError: ignored